// Mocks generated by Mockito 5.4.6 from annotations
// in ravecards/test/features/card/domain/usecases/get_card_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i7;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ravecards/core/error/failures.dart' as _i5;
import 'package:ravecards/features/card/domain/entities/card_entity.dart'
    as _i6;
import 'package:ravecards/features/card/domain/repositories/card_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [CardRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockCardRepository extends _i1.Mock implements _i3.CardRepository {
  MockCardRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.CardFailure, _i6.CardEntity>> getCard(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #getCard,
          [uid],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.CardFailure, _i6.CardEntity>>.value(
                _FakeEither_0<_i5.CardFailure, _i6.CardEntity>(
          this,
          Invocation.method(
            #getCard,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CardFailure, _i6.CardEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.CardFailure, _i6.CardEntity>> createCard({
    required String? uid,
    required String? displayName,
    required _i7.File? photo,
    required String? genre,
    required String? orientation,
    required String? relationshipStatus,
    required String? favoriteTheme,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #createCard,
          [],
          {
            #uid: uid,
            #displayName: displayName,
            #photo: photo,
            #genre: genre,
            #orientation: orientation,
            #relationshipStatus: relationshipStatus,
            #favoriteTheme: favoriteTheme,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.CardFailure, _i6.CardEntity>>.value(
                _FakeEither_0<_i5.CardFailure, _i6.CardEntity>(
          this,
          Invocation.method(
            #createCard,
            [],
            {
              #uid: uid,
              #displayName: displayName,
              #photo: photo,
              #genre: genre,
              #orientation: orientation,
              #relationshipStatus: relationshipStatus,
              #favoriteTheme: favoriteTheme,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CardFailure, _i6.CardEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.CardFailure, String>> refreshQrToken(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #refreshQrToken,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.CardFailure, String>>.value(
            _FakeEither_0<_i5.CardFailure, String>(
          this,
          Invocation.method(
            #refreshQrToken,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.CardFailure, String>>);

  @override
  _i4.Stream<_i6.CardEntity?> watchCard(String? uid) => (super.noSuchMethod(
        Invocation.method(
          #watchCard,
          [uid],
        ),
        returnValue: _i4.Stream<_i6.CardEntity?>.empty(),
      ) as _i4.Stream<_i6.CardEntity?>);
}
