// Mocks generated by Mockito 5.4.6 from annotations
// in ravecards/test/features/auth/domain/usecases/send_otp_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ravecards/core/error/failures.dart' as _i6;
import 'package:ravecards/features/auth/domain/entities/user_entity.dart'
    as _i5;
import 'package:ravecards/features/auth/domain/repositories/auth_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [AuthRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthRepository extends _i1.Mock implements _i3.AuthRepository {
  MockAuthRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i5.UserEntity?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i4.Stream<_i5.UserEntity?>.empty(),
      ) as _i4.Stream<_i5.UserEntity?>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, String>> sendOtp(String? phone) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendOtp,
          [phone],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.AuthFailure, String>>.value(
            _FakeEither_0<_i6.AuthFailure, String>(
          this,
          Invocation.method(
            #sendOtp,
            [phone],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.AuthFailure, String>>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserEntity>> verifyOtp({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtp,
          [],
          {
            #verificationId: verificationId,
            #smsCode: smsCode,
          },
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserEntity>>.value(
                _FakeEither_0<_i6.AuthFailure, _i5.UserEntity>(
          this,
          Invocation.method(
            #verifyOtp,
            [],
            {
              #verificationId: verificationId,
              #smsCode: smsCode,
            },
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserEntity>> signInWithGoogle() =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithGoogle,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserEntity>>.value(
                _FakeEither_0<_i6.AuthFailure, _i5.UserEntity>(
          this,
          Invocation.method(
            #signInWithGoogle,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.AuthFailure, _i5.UserEntity>>);

  @override
  _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>> signOut() =>
      (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i6.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #signOut,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i6.AuthFailure, _i2.Unit>>);
}
