// Mocks generated by Mockito 5.4.6 from annotations
// in ravecards/test/features/scan/presentation/cubit/scan_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ravecards/core/error/failures.dart' as _i5;
import 'package:ravecards/features/card/domain/entities/card_entity.dart'
    as _i7;
import 'package:ravecards/features/link/domain/entities/link_entity.dart'
    as _i12;
import 'package:ravecards/features/link/domain/usecases/watch_link.dart'
    as _i11;
import 'package:ravecards/features/scan/domain/entities/scan_result_entity.dart'
    as _i9;
import 'package:ravecards/features/scan/domain/usecases/confirm_link.dart'
    as _i10;
import 'package:ravecards/features/scan/domain/usecases/initiate_link.dart'
    as _i8;
import 'package:ravecards/features/scan/domain/usecases/preview_card.dart'
    as _i6;
import 'package:ravecards/features/scan/domain/usecases/validate_qr_token.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ValidateQrToken].
///
/// See the documentation for Mockito's code generation for more information.
class MockValidateQrToken extends _i1.Mock implements _i3.ValidateQrToken {
  MockValidateQrToken() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> call(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #call,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);
}

/// A class which mocks [PreviewCard].
///
/// See the documentation for Mockito's code generation for more information.
class MockPreviewCard extends _i1.Mock implements _i6.PreviewCard {
  MockPreviewCard() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.CardEntity>> call(String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i7.CardEntity>>.value(
            _FakeEither_0<_i5.Failure, _i7.CardEntity>(
          this,
          Invocation.method(
            #call,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.CardEntity>>);
}

/// A class which mocks [InitiateLink].
///
/// See the documentation for Mockito's code generation for more information.
class MockInitiateLink extends _i1.Mock implements _i8.InitiateLink {
  MockInitiateLink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i9.InitiateLinkResult>> call(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [token],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i9.InitiateLinkResult>>.value(
                _FakeEither_0<_i5.Failure, _i9.InitiateLinkResult>(
          this,
          Invocation.method(
            #call,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i9.InitiateLinkResult>>);
}

/// A class which mocks [ConfirmLink].
///
/// See the documentation for Mockito's code generation for more information.
class MockConfirmLink extends _i1.Mock implements _i10.ConfirmLink {
  MockConfirmLink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> call(
    String? linkId,
    int? durationHours,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [
            linkId,
            durationHours,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [
              linkId,
              durationHours,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}

/// A class which mocks [WatchLink].
///
/// See the documentation for Mockito's code generation for more information.
class MockWatchLink extends _i1.Mock implements _i11.WatchLink {
  MockWatchLink() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<_i2.Either<_i5.Failure, _i12.LinkEntity>> call(String? linkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [linkId],
        ),
        returnValue:
            _i4.Stream<_i2.Either<_i5.Failure, _i12.LinkEntity>>.empty(),
      ) as _i4.Stream<_i2.Either<_i5.Failure, _i12.LinkEntity>>);
}
