// Mocks generated by Mockito 5.4.6 from annotations
// in ravecards/test/features/scan/domain/usecases/scan_usecases_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ravecards/core/error/failures.dart' as _i5;
import 'package:ravecards/features/card/domain/entities/card_entity.dart'
    as _i6;
import 'package:ravecards/features/scan/domain/entities/scan_result_entity.dart'
    as _i7;
import 'package:ravecards/features/scan/domain/repositories/scan_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [ScanRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockScanRepository extends _i1.Mock implements _i3.ScanRepository {
  MockScanRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, String>> validateQrToken(String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #validateQrToken,
          [token],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, String>>.value(
            _FakeEither_0<_i5.Failure, String>(
          this,
          Invocation.method(
            #validateQrToken,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, String>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.CardEntity>> previewCard(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #previewCard,
          [uid],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.CardEntity>>.value(
            _FakeEither_0<_i5.Failure, _i6.CardEntity>(
          this,
          Invocation.method(
            #previewCard,
            [uid],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i6.CardEntity>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i7.InitiateLinkResult>> initiateLink(
          String? token) =>
      (super.noSuchMethod(
        Invocation.method(
          #initiateLink,
          [token],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.Failure, _i7.InitiateLinkResult>>.value(
                _FakeEither_0<_i5.Failure, _i7.InitiateLinkResult>(
          this,
          Invocation.method(
            #initiateLink,
            [token],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i7.InitiateLinkResult>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>> confirmLink(
    String? linkId,
    int? durationHours,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmLink,
          [
            linkId,
            durationHours,
          ],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>.value(
            _FakeEither_0<_i5.Failure, _i2.Unit>(
          this,
          Invocation.method(
            #confirmLink,
            [
              linkId,
              durationHours,
            ],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.Failure, _i2.Unit>>);
}
