// Mocks generated by Mockito 5.4.6 from annotations
// in ravecards/test/features/link/domain/usecases/watch_my_links_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:dartz/dartz.dart' as _i4;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ravecards/core/error/failures.dart' as _i5;
import 'package:ravecards/features/link/domain/entities/link_entity.dart'
    as _i6;
import 'package:ravecards/features/link/domain/repositories/link_repository.dart'
    as _i2;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [LinkRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockLinkRepository extends _i1.Mock implements _i2.LinkRepository {
  MockLinkRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<_i4.Either<_i5.Failure, List<_i6.LinkEntity>>> watchMyLinks(
          String? uid) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchMyLinks,
          [uid],
        ),
        returnValue:
            _i3.Stream<_i4.Either<_i5.Failure, List<_i6.LinkEntity>>>.empty(),
      ) as _i3.Stream<_i4.Either<_i5.Failure, List<_i6.LinkEntity>>>);

  @override
  _i3.Stream<_i4.Either<_i5.Failure, _i6.LinkEntity>> watchLink(
          String? linkId) =>
      (super.noSuchMethod(
        Invocation.method(
          #watchLink,
          [linkId],
        ),
        returnValue:
            _i3.Stream<_i4.Either<_i5.Failure, _i6.LinkEntity>>.empty(),
      ) as _i3.Stream<_i4.Either<_i5.Failure, _i6.LinkEntity>>);
}
