// Mocks generated by Mockito 5.4.6 from annotations
// in ravecards/test/features/auth/presentation/cubit/auth_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:ravecards/core/error/failures.dart' as _i5;
import 'package:ravecards/features/auth/domain/entities/user_entity.dart'
    as _i7;
import 'package:ravecards/features/auth/domain/usecases/send_otp.dart' as _i3;
import 'package:ravecards/features/auth/domain/usecases/sign_in_with_google.dart'
    as _i8;
import 'package:ravecards/features/auth/domain/usecases/sign_out.dart' as _i9;
import 'package:ravecards/features/auth/domain/usecases/verify_otp.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [SendOtp].
///
/// See the documentation for Mockito's code generation for more information.
class MockSendOtp extends _i1.Mock implements _i3.SendOtp {
  MockSendOtp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, String>> call(String? phone) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [phone],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, String>>.value(
            _FakeEither_0<_i5.AuthFailure, String>(
          this,
          Invocation.method(
            #call,
            [phone],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, String>>);
}

/// A class which mocks [VerifyOtp].
///
/// See the documentation for Mockito's code generation for more information.
class MockVerifyOtp extends _i1.Mock implements _i6.VerifyOtp {
  MockVerifyOtp() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i7.UserEntity>> call(
          _i6.VerifyOtpParams? params) =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [params],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AuthFailure, _i7.UserEntity>>.value(
                _FakeEither_0<_i5.AuthFailure, _i7.UserEntity>(
          this,
          Invocation.method(
            #call,
            [params],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i7.UserEntity>>);
}

/// A class which mocks [SignInWithGoogle].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignInWithGoogle extends _i1.Mock implements _i8.SignInWithGoogle {
  MockSignInWithGoogle() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i7.UserEntity>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue:
            _i4.Future<_i2.Either<_i5.AuthFailure, _i7.UserEntity>>.value(
                _FakeEither_0<_i5.AuthFailure, _i7.UserEntity>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i7.UserEntity>>);
}

/// A class which mocks [SignOut].
///
/// See the documentation for Mockito's code generation for more information.
class MockSignOut extends _i1.Mock implements _i9.SignOut {
  MockSignOut() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>> call() =>
      (super.noSuchMethod(
        Invocation.method(
          #call,
          [],
        ),
        returnValue: _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>.value(
            _FakeEither_0<_i5.AuthFailure, _i2.Unit>(
          this,
          Invocation.method(
            #call,
            [],
          ),
        )),
      ) as _i4.Future<_i2.Either<_i5.AuthFailure, _i2.Unit>>);
}
